name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "MY_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --self-contained true -p:PublishSingleFile=true --runtime win-x64 -c Release -o "outputs"
    - name: Pack
      run: 7z a -tzip "outputs.zip" "./outputs/*"
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "outputs.zip"
        tag_name: nightly-release-${{ env.MY_DATE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}